/* soapStub.h
   Generated by gSOAP 2.7.15 from tempoAPI.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_ns1	"http://TempoAPI"
#include "stdsoap2.h"

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not redeclare here */

#endif

#ifndef SOAP_TYPE__ns1__getMessages
#define SOAP_TYPE__ns1__getMessages (7)
/* ns1:getMessages */
class SOAP_CMAC _ns1__getMessages
{
public:
	char *listeIdMessage;	/* required element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 7; } /* = unique id SOAP_TYPE__ns1__getMessages */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getMessages() : listeIdMessage(NULL), soap(NULL) { this->soap_default(NULL); }
	virtual ~_ns1__getMessages() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getMessagesResponse
#define SOAP_TYPE__ns1__getMessagesResponse (8)
/* ns1:getMessagesResponse */
class SOAP_CMAC _ns1__getMessagesResponse
{
public:
	int __sizegetMessagesReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* sequence of elements <getMessagesReturn> */
	char **getMessagesReturn;	/* required element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 8; } /* = unique id SOAP_TYPE__ns1__getMessagesResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getMessagesResponse() : __sizegetMessagesReturn(0), getMessagesReturn(NULL), soap(NULL) { this->soap_default(NULL); }
	virtual ~_ns1__getMessagesResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getListeLignes
#define SOAP_TYPE__ns1__getListeLignes (9)
/* ns1:getListeLignes */
class SOAP_CMAC _ns1__getListeLignes
{
public:
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 9; } /* = unique id SOAP_TYPE__ns1__getListeLignes */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getListeLignes() : soap(NULL) { this->soap_default(NULL); }
	virtual ~_ns1__getListeLignes() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getListeLignesResponse
#define SOAP_TYPE__ns1__getListeLignesResponse (10)
/* ns1:getListeLignesResponse */
class SOAP_CMAC _ns1__getListeLignesResponse
{
public:
	int __sizegetListeLignesReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* sequence of elements <getListeLignesReturn> */
	char **getListeLignesReturn;	/* required element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 10; } /* = unique id SOAP_TYPE__ns1__getListeLignesResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getListeLignesResponse() : __sizegetListeLignesReturn(0), getListeLignesReturn(NULL), soap(NULL) { this->soap_default(NULL); }
	virtual ~_ns1__getListeLignesResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getListeStations
#define SOAP_TYPE__ns1__getListeStations (11)
/* ns1:getListeStations */
class SOAP_CMAC _ns1__getListeStations
{
public:
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 11; } /* = unique id SOAP_TYPE__ns1__getListeStations */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getListeStations() : soap(NULL) { this->soap_default(NULL); }
	virtual ~_ns1__getListeStations() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getListeStationsResponse
#define SOAP_TYPE__ns1__getListeStationsResponse (12)
/* ns1:getListeStationsResponse */
class SOAP_CMAC _ns1__getListeStationsResponse
{
public:
	int __sizegetListeStationsReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* sequence of elements <getListeStationsReturn> */
	char **getListeStationsReturn;	/* required element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 12; } /* = unique id SOAP_TYPE__ns1__getListeStationsResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getListeStationsResponse() : __sizegetListeStationsReturn(0), getListeStationsReturn(NULL), soap(NULL) { this->soap_default(NULL); }
	virtual ~_ns1__getListeStationsResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getListeStationsParLigne
#define SOAP_TYPE__ns1__getListeStationsParLigne (13)
/* ns1:getListeStationsParLigne */
class SOAP_CMAC _ns1__getListeStationsParLigne
{
public:
	char *ligne;	/* required element of type xsd:string */
	char *sens;	/* required element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 13; } /* = unique id SOAP_TYPE__ns1__getListeStationsParLigne */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getListeStationsParLigne() : ligne(NULL), sens(NULL), soap(NULL) { this->soap_default(NULL); }
	virtual ~_ns1__getListeStationsParLigne() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getListeStationsParLigneResponse
#define SOAP_TYPE__ns1__getListeStationsParLigneResponse (14)
/* ns1:getListeStationsParLigneResponse */
class SOAP_CMAC _ns1__getListeStationsParLigneResponse
{
public:
	int __sizegetListeStationsParLigneReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* sequence of elements <getListeStationsParLigneReturn> */
	char **getListeStationsParLigneReturn;	/* required element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 14; } /* = unique id SOAP_TYPE__ns1__getListeStationsParLigneResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getListeStationsParLigneResponse() : __sizegetListeStationsParLigneReturn(0), getListeStationsParLigneReturn(NULL), soap(NULL) { this->soap_default(NULL); }
	virtual ~_ns1__getListeStationsParLigneResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getStationsLesPlusProches
#define SOAP_TYPE__ns1__getStationsLesPlusProches (15)
/* ns1:getStationsLesPlusProches */
class SOAP_CMAC _ns1__getStationsLesPlusProches
{
public:
	char *Longitute;	/* required element of type xsd:string */
	char *Latitude;	/* required element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 15; } /* = unique id SOAP_TYPE__ns1__getStationsLesPlusProches */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getStationsLesPlusProches() : Longitute(NULL), Latitude(NULL), soap(NULL) { this->soap_default(NULL); }
	virtual ~_ns1__getStationsLesPlusProches() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getStationsLesPlusProchesResponse
#define SOAP_TYPE__ns1__getStationsLesPlusProchesResponse (16)
/* ns1:getStationsLesPlusProchesResponse */
class SOAP_CMAC _ns1__getStationsLesPlusProchesResponse
{
public:
	int __sizegetStationsLesPlusProchesReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* sequence of elements <getStationsLesPlusProchesReturn> */
	char **getStationsLesPlusProchesReturn;	/* required element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 16; } /* = unique id SOAP_TYPE__ns1__getStationsLesPlusProchesResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getStationsLesPlusProchesResponse() : __sizegetStationsLesPlusProchesReturn(0), getStationsLesPlusProchesReturn(NULL), soap(NULL) { this->soap_default(NULL); }
	virtual ~_ns1__getStationsLesPlusProchesResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getTempsParStation
#define SOAP_TYPE__ns1__getTempsParStation (17)
/* ns1:getTempsParStation */
class SOAP_CMAC _ns1__getTempsParStation
{
public:
	char *nomStation;	/* required element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 17; } /* = unique id SOAP_TYPE__ns1__getTempsParStation */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getTempsParStation() : nomStation(NULL), soap(NULL) { this->soap_default(NULL); }
	virtual ~_ns1__getTempsParStation() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getTempsParStationResponse
#define SOAP_TYPE__ns1__getTempsParStationResponse (18)
/* ns1:getTempsParStationResponse */
class SOAP_CMAC _ns1__getTempsParStationResponse
{
public:
	int __sizegetTempsParStationReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* sequence of elements <getTempsParStationReturn> */
	char **getTempsParStationReturn;	/* required element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 18; } /* = unique id SOAP_TYPE__ns1__getTempsParStationResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getTempsParStationResponse() : __sizegetTempsParStationReturn(0), getTempsParStationReturn(NULL), soap(NULL) { this->soap_default(NULL); }
	virtual ~_ns1__getTempsParStationResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getInfoTrafic
#define SOAP_TYPE__ns1__getInfoTrafic (19)
/* ns1:getInfoTrafic */
class SOAP_CMAC _ns1__getInfoTrafic
{
public:
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 19; } /* = unique id SOAP_TYPE__ns1__getInfoTrafic */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getInfoTrafic() : soap(NULL) { this->soap_default(NULL); }
	virtual ~_ns1__getInfoTrafic() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getInfoTraficResponse
#define SOAP_TYPE__ns1__getInfoTraficResponse (20)
/* ns1:getInfoTraficResponse */
class SOAP_CMAC _ns1__getInfoTraficResponse
{
public:
	int __sizegetInfoTraficReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* sequence of elements <getInfoTraficReturn> */
	char **getInfoTraficReturn;	/* required element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 20; } /* = unique id SOAP_TYPE__ns1__getInfoTraficResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getInfoTraficResponse() : __sizegetInfoTraficReturn(0), getInfoTraficReturn(NULL), soap(NULL) { this->soap_default(NULL); }
	virtual ~_ns1__getInfoTraficResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getLigneStationBornePerso
#define SOAP_TYPE__ns1__getLigneStationBornePerso (21)
/* ns1:getLigneStationBornePerso */
class SOAP_CMAC _ns1__getLigneStationBornePerso
{
public:
	char *Idenditifiant;	/* required element of type xsd:string */
	char *MotDePasseMD5;	/* required element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 21; } /* = unique id SOAP_TYPE__ns1__getLigneStationBornePerso */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getLigneStationBornePerso() : Idenditifiant(NULL), MotDePasseMD5(NULL), soap(NULL) { this->soap_default(NULL); }
	virtual ~_ns1__getLigneStationBornePerso() { }
};
#endif

#ifndef SOAP_TYPE__ns1__getLigneStationBornePersoResponse
#define SOAP_TYPE__ns1__getLigneStationBornePersoResponse (22)
/* ns1:getLigneStationBornePersoResponse */
class SOAP_CMAC _ns1__getLigneStationBornePersoResponse
{
public:
	int __sizegetLigneStationBornePersoReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* sequence of elements <getLigneStationBornePersoReturn> */
	char **getLigneStationBornePersoReturn;	/* required element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 22; } /* = unique id SOAP_TYPE__ns1__getLigneStationBornePersoResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__getLigneStationBornePersoResponse() : __sizegetLigneStationBornePersoReturn(0), getLigneStationBornePersoReturn(NULL), soap(NULL) { this->soap_default(NULL); }
	virtual ~_ns1__getLigneStationBornePersoResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__addLigneStationBornePerso
#define SOAP_TYPE__ns1__addLigneStationBornePerso (23)
/* ns1:addLigneStationBornePerso */
class SOAP_CMAC _ns1__addLigneStationBornePerso
{
public:
	char *Idenditifiant;	/* required element of type xsd:string */
	char *MotDePasseMD5;	/* required element of type xsd:string */
	char *nomStation;	/* required element of type xsd:string */
	char *ligne;	/* required element of type xsd:string */
	char *sens;	/* required element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 23; } /* = unique id SOAP_TYPE__ns1__addLigneStationBornePerso */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__addLigneStationBornePerso() : Idenditifiant(NULL), MotDePasseMD5(NULL), nomStation(NULL), ligne(NULL), sens(NULL), soap(NULL) { this->soap_default(NULL); }
	virtual ~_ns1__addLigneStationBornePerso() { }
};
#endif

#ifndef SOAP_TYPE__ns1__addLigneStationBornePersoResponse
#define SOAP_TYPE__ns1__addLigneStationBornePersoResponse (24)
/* ns1:addLigneStationBornePersoResponse */
class SOAP_CMAC _ns1__addLigneStationBornePersoResponse
{
public:
	int addLigneStationBornePersoReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 24; } /* = unique id SOAP_TYPE__ns1__addLigneStationBornePersoResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__addLigneStationBornePersoResponse() : addLigneStationBornePersoReturn(0), soap(NULL) { this->soap_default(NULL); }
	virtual ~_ns1__addLigneStationBornePersoResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__deleteLigneStationBornePerso
#define SOAP_TYPE__ns1__deleteLigneStationBornePerso (25)
/* ns1:deleteLigneStationBornePerso */
class SOAP_CMAC _ns1__deleteLigneStationBornePerso
{
public:
	char *Idenditifiant;	/* required element of type xsd:string */
	char *MotDePasseMD5;	/* required element of type xsd:string */
	char *nomStation;	/* required element of type xsd:string */
	char *ligne;	/* required element of type xsd:string */
	char *sens;	/* required element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 25; } /* = unique id SOAP_TYPE__ns1__deleteLigneStationBornePerso */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__deleteLigneStationBornePerso() : Idenditifiant(NULL), MotDePasseMD5(NULL), nomStation(NULL), ligne(NULL), sens(NULL), soap(NULL) { this->soap_default(NULL); }
	virtual ~_ns1__deleteLigneStationBornePerso() { }
};
#endif

#ifndef SOAP_TYPE__ns1__deleteLigneStationBornePersoResponse
#define SOAP_TYPE__ns1__deleteLigneStationBornePersoResponse (26)
/* ns1:deleteLigneStationBornePersoResponse */
class SOAP_CMAC _ns1__deleteLigneStationBornePersoResponse
{
public:
	int deleteLigneStationBornePersoReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 26; } /* = unique id SOAP_TYPE__ns1__deleteLigneStationBornePersoResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__deleteLigneStationBornePersoResponse() : deleteLigneStationBornePersoReturn(0), soap(NULL) { this->soap_default(NULL); }
	virtual ~_ns1__deleteLigneStationBornePersoResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__createBornePerso
#define SOAP_TYPE__ns1__createBornePerso (27)
/* ns1:createBornePerso */
class SOAP_CMAC _ns1__createBornePerso
{
public:
	char *Idenditifiant;	/* required element of type xsd:string */
	char *MotDePasseMD5;	/* required element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 27; } /* = unique id SOAP_TYPE__ns1__createBornePerso */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__createBornePerso() : Idenditifiant(NULL), MotDePasseMD5(NULL), soap(NULL) { this->soap_default(NULL); }
	virtual ~_ns1__createBornePerso() { }
};
#endif

#ifndef SOAP_TYPE__ns1__createBornePersoResponse
#define SOAP_TYPE__ns1__createBornePersoResponse (28)
/* ns1:createBornePersoResponse */
class SOAP_CMAC _ns1__createBornePersoResponse
{
public:
	int createBornePersoReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 28; } /* = unique id SOAP_TYPE__ns1__createBornePersoResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__createBornePersoResponse() : createBornePersoReturn(0), soap(NULL) { this->soap_default(NULL); }
	virtual ~_ns1__createBornePersoResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__verifBornePerso
#define SOAP_TYPE__ns1__verifBornePerso (29)
/* ns1:verifBornePerso */
class SOAP_CMAC _ns1__verifBornePerso
{
public:
	char *Idenditifiant;	/* required element of type xsd:string */
	char *MotDePasseMD5;	/* required element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 29; } /* = unique id SOAP_TYPE__ns1__verifBornePerso */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__verifBornePerso() : Idenditifiant(NULL), MotDePasseMD5(NULL), soap(NULL) { this->soap_default(NULL); }
	virtual ~_ns1__verifBornePerso() { }
};
#endif

#ifndef SOAP_TYPE__ns1__verifBornePersoResponse
#define SOAP_TYPE__ns1__verifBornePersoResponse (30)
/* ns1:verifBornePersoResponse */
class SOAP_CMAC _ns1__verifBornePersoResponse
{
public:
	int verifBornePersoReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 30; } /* = unique id SOAP_TYPE__ns1__verifBornePersoResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__verifBornePersoResponse() : verifBornePersoReturn(0), soap(NULL) { this->soap_default(NULL); }
	virtual ~_ns1__verifBornePersoResponse() { }
};
#endif

#ifndef SOAP_TYPE___ns1__getMessages
#define SOAP_TYPE___ns1__getMessages (36)
/* Operation wrapper: */
struct __ns1__getMessages
{
public:
	_ns1__getMessages *ns1__getMessages;	/* optional element of type ns1:getMessages */
};
#endif

#ifndef SOAP_TYPE___ns1__getListeLignes
#define SOAP_TYPE___ns1__getListeLignes (40)
/* Operation wrapper: */
struct __ns1__getListeLignes
{
public:
	_ns1__getListeLignes *ns1__getListeLignes;	/* optional element of type ns1:getListeLignes */
};
#endif

#ifndef SOAP_TYPE___ns1__getListeStations
#define SOAP_TYPE___ns1__getListeStations (44)
/* Operation wrapper: */
struct __ns1__getListeStations
{
public:
	_ns1__getListeStations *ns1__getListeStations;	/* optional element of type ns1:getListeStations */
};
#endif

#ifndef SOAP_TYPE___ns1__getListeStationsParLigne
#define SOAP_TYPE___ns1__getListeStationsParLigne (48)
/* Operation wrapper: */
struct __ns1__getListeStationsParLigne
{
public:
	_ns1__getListeStationsParLigne *ns1__getListeStationsParLigne;	/* optional element of type ns1:getListeStationsParLigne */
};
#endif

#ifndef SOAP_TYPE___ns1__getStationsLesPlusProches
#define SOAP_TYPE___ns1__getStationsLesPlusProches (52)
/* Operation wrapper: */
struct __ns1__getStationsLesPlusProches
{
public:
	_ns1__getStationsLesPlusProches *ns1__getStationsLesPlusProches;	/* optional element of type ns1:getStationsLesPlusProches */
};
#endif

#ifndef SOAP_TYPE___ns1__getTempsParStation
#define SOAP_TYPE___ns1__getTempsParStation (56)
/* Operation wrapper: */
struct __ns1__getTempsParStation
{
public:
	_ns1__getTempsParStation *ns1__getTempsParStation;	/* optional element of type ns1:getTempsParStation */
};
#endif

#ifndef SOAP_TYPE___ns1__getInfoTrafic
#define SOAP_TYPE___ns1__getInfoTrafic (60)
/* Operation wrapper: */
struct __ns1__getInfoTrafic
{
public:
	_ns1__getInfoTrafic *ns1__getInfoTrafic;	/* optional element of type ns1:getInfoTrafic */
};
#endif

#ifndef SOAP_TYPE___ns1__getLigneStationBornePerso
#define SOAP_TYPE___ns1__getLigneStationBornePerso (64)
/* Operation wrapper: */
struct __ns1__getLigneStationBornePerso
{
public:
	_ns1__getLigneStationBornePerso *ns1__getLigneStationBornePerso;	/* optional element of type ns1:getLigneStationBornePerso */
};
#endif

#ifndef SOAP_TYPE___ns1__addLigneStationBornePerso
#define SOAP_TYPE___ns1__addLigneStationBornePerso (68)
/* Operation wrapper: */
struct __ns1__addLigneStationBornePerso
{
public:
	_ns1__addLigneStationBornePerso *ns1__addLigneStationBornePerso;	/* optional element of type ns1:addLigneStationBornePerso */
};
#endif

#ifndef SOAP_TYPE___ns1__deleteLigneStationBornePerso
#define SOAP_TYPE___ns1__deleteLigneStationBornePerso (72)
/* Operation wrapper: */
struct __ns1__deleteLigneStationBornePerso
{
public:
	_ns1__deleteLigneStationBornePerso *ns1__deleteLigneStationBornePerso;	/* optional element of type ns1:deleteLigneStationBornePerso */
};
#endif

#ifndef SOAP_TYPE___ns1__createBornePerso
#define SOAP_TYPE___ns1__createBornePerso (76)
/* Operation wrapper: */
struct __ns1__createBornePerso
{
public:
	_ns1__createBornePerso *ns1__createBornePerso;	/* optional element of type ns1:createBornePerso */
};
#endif

#ifndef SOAP_TYPE___ns1__verifBornePerso
#define SOAP_TYPE___ns1__verifBornePerso (80)
/* Operation wrapper: */
struct __ns1__verifBornePerso
{
public:
	_ns1__verifBornePerso *ns1__verifBornePerso;	/* optional element of type ns1:verifBornePerso */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (81)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (82)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (84)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (87)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (88)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Stubs                                                                      *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getMessages(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getMessages *ns1__getMessages, _ns1__getMessagesResponse *ns1__getMessagesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getListeLignes(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getListeLignes *ns1__getListeLignes, _ns1__getListeLignesResponse *ns1__getListeLignesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getListeStations(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getListeStations *ns1__getListeStations, _ns1__getListeStationsResponse *ns1__getListeStationsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getListeStationsParLigne(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getListeStationsParLigne *ns1__getListeStationsParLigne, _ns1__getListeStationsParLigneResponse *ns1__getListeStationsParLigneResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getStationsLesPlusProches(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getStationsLesPlusProches *ns1__getStationsLesPlusProches, _ns1__getStationsLesPlusProchesResponse *ns1__getStationsLesPlusProchesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getTempsParStation(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getTempsParStation *ns1__getTempsParStation, _ns1__getTempsParStationResponse *ns1__getTempsParStationResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getInfoTrafic(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getInfoTrafic *ns1__getInfoTrafic, _ns1__getInfoTraficResponse *ns1__getInfoTraficResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getLigneStationBornePerso(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getLigneStationBornePerso *ns1__getLigneStationBornePerso, _ns1__getLigneStationBornePersoResponse *ns1__getLigneStationBornePersoResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__addLigneStationBornePerso(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__addLigneStationBornePerso *ns1__addLigneStationBornePerso, _ns1__addLigneStationBornePersoResponse *ns1__addLigneStationBornePersoResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__deleteLigneStationBornePerso(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__deleteLigneStationBornePerso *ns1__deleteLigneStationBornePerso, _ns1__deleteLigneStationBornePersoResponse *ns1__deleteLigneStationBornePersoResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__createBornePerso(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__createBornePerso *ns1__createBornePerso, _ns1__createBornePersoResponse *ns1__createBornePersoResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__verifBornePerso(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__verifBornePerso *ns1__verifBornePerso, _ns1__verifBornePersoResponse *ns1__verifBornePersoResponse);

#endif

/* End of soapStub.h */
