/* soapClient.cpp
   Generated by gSOAP 2.7.15 from TempoAPI.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.7.15 2010-03-18 13:33:34 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getMessages(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getMessages *ns1__getMessages, _ns1__getMessagesResponse *ns1__getMessagesResponse)
{	struct __ns1__getMessages soap_tmp___ns1__getMessages;
	if (!soap_endpoint)
		soap_endpoint = "http://81.255.131.38/TempoAPI/services/TempoAPI";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getMessages.ns1__getMessages = ns1__getMessages;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getMessages(soap, &soap_tmp___ns1__getMessages);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getMessages(soap, &soap_tmp___ns1__getMessages, "-ns1:getMessages", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getMessages(soap, &soap_tmp___ns1__getMessages, "-ns1:getMessages", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getMessagesResponse)
		return soap_closesock(soap);
	ns1__getMessagesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getMessagesResponse->soap_get(soap, "ns1:getMessagesResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getListeLignes(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getListeLignes *ns1__getListeLignes, _ns1__getListeLignesResponse *ns1__getListeLignesResponse)
{	struct __ns1__getListeLignes soap_tmp___ns1__getListeLignes;
	if (!soap_endpoint)
		soap_endpoint = "http://81.255.131.38/TempoAPI/services/TempoAPI";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getListeLignes.ns1__getListeLignes = ns1__getListeLignes;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getListeLignes(soap, &soap_tmp___ns1__getListeLignes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getListeLignes(soap, &soap_tmp___ns1__getListeLignes, "-ns1:getListeLignes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getListeLignes(soap, &soap_tmp___ns1__getListeLignes, "-ns1:getListeLignes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getListeLignesResponse)
		return soap_closesock(soap);
	ns1__getListeLignesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getListeLignesResponse->soap_get(soap, "ns1:getListeLignesResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getListeStations(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getListeStations *ns1__getListeStations, _ns1__getListeStationsResponse *ns1__getListeStationsResponse)
{	struct __ns1__getListeStations soap_tmp___ns1__getListeStations;
	if (!soap_endpoint)
		soap_endpoint = "http://81.255.131.38/TempoAPI/services/TempoAPI";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getListeStations.ns1__getListeStations = ns1__getListeStations;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getListeStations(soap, &soap_tmp___ns1__getListeStations);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getListeStations(soap, &soap_tmp___ns1__getListeStations, "-ns1:getListeStations", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getListeStations(soap, &soap_tmp___ns1__getListeStations, "-ns1:getListeStations", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getListeStationsResponse)
		return soap_closesock(soap);
	ns1__getListeStationsResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getListeStationsResponse->soap_get(soap, "ns1:getListeStationsResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getListeStationsParLigne(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getListeStationsParLigne *ns1__getListeStationsParLigne, _ns1__getListeStationsParLigneResponse *ns1__getListeStationsParLigneResponse)
{	struct __ns1__getListeStationsParLigne soap_tmp___ns1__getListeStationsParLigne;
	if (!soap_endpoint)
		soap_endpoint = "http://81.255.131.38/TempoAPI/services/TempoAPI";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getListeStationsParLigne.ns1__getListeStationsParLigne = ns1__getListeStationsParLigne;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getListeStationsParLigne(soap, &soap_tmp___ns1__getListeStationsParLigne);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getListeStationsParLigne(soap, &soap_tmp___ns1__getListeStationsParLigne, "-ns1:getListeStationsParLigne", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getListeStationsParLigne(soap, &soap_tmp___ns1__getListeStationsParLigne, "-ns1:getListeStationsParLigne", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getListeStationsParLigneResponse)
		return soap_closesock(soap);
	ns1__getListeStationsParLigneResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getListeStationsParLigneResponse->soap_get(soap, "ns1:getListeStationsParLigneResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getListeStationsProches(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getListeStationsProches *ns1__getListeStationsProches, _ns1__getListeStationsProchesResponse *ns1__getListeStationsProchesResponse)
{	struct __ns1__getListeStationsProches soap_tmp___ns1__getListeStationsProches;
	if (!soap_endpoint)
		soap_endpoint = "http://81.255.131.38/TempoAPI/services/TempoAPI";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getListeStationsProches.ns1__getListeStationsProches = ns1__getListeStationsProches;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getListeStationsProches(soap, &soap_tmp___ns1__getListeStationsProches);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getListeStationsProches(soap, &soap_tmp___ns1__getListeStationsProches, "-ns1:getListeStationsProches", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getListeStationsProches(soap, &soap_tmp___ns1__getListeStationsProches, "-ns1:getListeStationsProches", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getListeStationsProchesResponse)
		return soap_closesock(soap);
	ns1__getListeStationsProchesResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getListeStationsProchesResponse->soap_get(soap, "ns1:getListeStationsProchesResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getTempsParStation(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getTempsParStation *ns1__getTempsParStation, _ns1__getTempsParStationResponse *ns1__getTempsParStationResponse)
{	struct __ns1__getTempsParStation soap_tmp___ns1__getTempsParStation;
	if (!soap_endpoint)
		soap_endpoint = "http://81.255.131.38/TempoAPI/services/TempoAPI";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getTempsParStation.ns1__getTempsParStation = ns1__getTempsParStation;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getTempsParStation(soap, &soap_tmp___ns1__getTempsParStation);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getTempsParStation(soap, &soap_tmp___ns1__getTempsParStation, "-ns1:getTempsParStation", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getTempsParStation(soap, &soap_tmp___ns1__getTempsParStation, "-ns1:getTempsParStation", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getTempsParStationResponse)
		return soap_closesock(soap);
	ns1__getTempsParStationResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getTempsParStationResponse->soap_get(soap, "ns1:getTempsParStationResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getInfoTrafic(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getInfoTrafic *ns1__getInfoTrafic, _ns1__getInfoTraficResponse *ns1__getInfoTraficResponse)
{	struct __ns1__getInfoTrafic soap_tmp___ns1__getInfoTrafic;
	if (!soap_endpoint)
		soap_endpoint = "http://81.255.131.38/TempoAPI/services/TempoAPI";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getInfoTrafic.ns1__getInfoTrafic = ns1__getInfoTrafic;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getInfoTrafic(soap, &soap_tmp___ns1__getInfoTrafic);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getInfoTrafic(soap, &soap_tmp___ns1__getInfoTrafic, "-ns1:getInfoTrafic", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getInfoTrafic(soap, &soap_tmp___ns1__getInfoTrafic, "-ns1:getInfoTrafic", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getInfoTraficResponse)
		return soap_closesock(soap);
	ns1__getInfoTraficResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getInfoTraficResponse->soap_get(soap, "ns1:getInfoTraficResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getLigneStationBornePerso(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__getLigneStationBornePerso *ns1__getLigneStationBornePerso, _ns1__getLigneStationBornePersoResponse *ns1__getLigneStationBornePersoResponse)
{	struct __ns1__getLigneStationBornePerso soap_tmp___ns1__getLigneStationBornePerso;
	if (!soap_endpoint)
		soap_endpoint = "http://81.255.131.38/TempoAPI/services/TempoAPI";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getLigneStationBornePerso.ns1__getLigneStationBornePerso = ns1__getLigneStationBornePerso;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getLigneStationBornePerso(soap, &soap_tmp___ns1__getLigneStationBornePerso);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getLigneStationBornePerso(soap, &soap_tmp___ns1__getLigneStationBornePerso, "-ns1:getLigneStationBornePerso", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getLigneStationBornePerso(soap, &soap_tmp___ns1__getLigneStationBornePerso, "-ns1:getLigneStationBornePerso", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getLigneStationBornePersoResponse)
		return soap_closesock(soap);
	ns1__getLigneStationBornePersoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getLigneStationBornePersoResponse->soap_get(soap, "ns1:getLigneStationBornePersoResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__addLigneStationBornePerso(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__addLigneStationBornePerso *ns1__addLigneStationBornePerso, _ns1__addLigneStationBornePersoResponse *ns1__addLigneStationBornePersoResponse)
{	struct __ns1__addLigneStationBornePerso soap_tmp___ns1__addLigneStationBornePerso;
	if (!soap_endpoint)
		soap_endpoint = "http://81.255.131.38/TempoAPI/services/TempoAPI";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__addLigneStationBornePerso.ns1__addLigneStationBornePerso = ns1__addLigneStationBornePerso;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__addLigneStationBornePerso(soap, &soap_tmp___ns1__addLigneStationBornePerso);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__addLigneStationBornePerso(soap, &soap_tmp___ns1__addLigneStationBornePerso, "-ns1:addLigneStationBornePerso", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__addLigneStationBornePerso(soap, &soap_tmp___ns1__addLigneStationBornePerso, "-ns1:addLigneStationBornePerso", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__addLigneStationBornePersoResponse)
		return soap_closesock(soap);
	ns1__addLigneStationBornePersoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__addLigneStationBornePersoResponse->soap_get(soap, "ns1:addLigneStationBornePersoResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__deleteLigneStationBornePerso(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__deleteLigneStationBornePerso *ns1__deleteLigneStationBornePerso, _ns1__deleteLigneStationBornePersoResponse *ns1__deleteLigneStationBornePersoResponse)
{	struct __ns1__deleteLigneStationBornePerso soap_tmp___ns1__deleteLigneStationBornePerso;
	if (!soap_endpoint)
		soap_endpoint = "http://81.255.131.38/TempoAPI/services/TempoAPI";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__deleteLigneStationBornePerso.ns1__deleteLigneStationBornePerso = ns1__deleteLigneStationBornePerso;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__deleteLigneStationBornePerso(soap, &soap_tmp___ns1__deleteLigneStationBornePerso);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__deleteLigneStationBornePerso(soap, &soap_tmp___ns1__deleteLigneStationBornePerso, "-ns1:deleteLigneStationBornePerso", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__deleteLigneStationBornePerso(soap, &soap_tmp___ns1__deleteLigneStationBornePerso, "-ns1:deleteLigneStationBornePerso", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__deleteLigneStationBornePersoResponse)
		return soap_closesock(soap);
	ns1__deleteLigneStationBornePersoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__deleteLigneStationBornePersoResponse->soap_get(soap, "ns1:deleteLigneStationBornePersoResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__createBornePerso(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__createBornePerso *ns1__createBornePerso, _ns1__createBornePersoResponse *ns1__createBornePersoResponse)
{	struct __ns1__createBornePerso soap_tmp___ns1__createBornePerso;
	if (!soap_endpoint)
		soap_endpoint = "http://81.255.131.38/TempoAPI/services/TempoAPI";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__createBornePerso.ns1__createBornePerso = ns1__createBornePerso;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__createBornePerso(soap, &soap_tmp___ns1__createBornePerso);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__createBornePerso(soap, &soap_tmp___ns1__createBornePerso, "-ns1:createBornePerso", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__createBornePerso(soap, &soap_tmp___ns1__createBornePerso, "-ns1:createBornePerso", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__createBornePersoResponse)
		return soap_closesock(soap);
	ns1__createBornePersoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__createBornePersoResponse->soap_get(soap, "ns1:createBornePersoResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__verifBornePerso(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__verifBornePerso *ns1__verifBornePerso, _ns1__verifBornePersoResponse *ns1__verifBornePersoResponse)
{	struct __ns1__verifBornePerso soap_tmp___ns1__verifBornePerso;
	if (!soap_endpoint)
		soap_endpoint = "http://81.255.131.38/TempoAPI/services/TempoAPI";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__verifBornePerso.ns1__verifBornePerso = ns1__verifBornePerso;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__verifBornePerso(soap, &soap_tmp___ns1__verifBornePerso);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__verifBornePerso(soap, &soap_tmp___ns1__verifBornePerso, "-ns1:verifBornePerso", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__verifBornePerso(soap, &soap_tmp___ns1__verifBornePerso, "-ns1:verifBornePerso", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__verifBornePersoResponse)
		return soap_closesock(soap);
	ns1__verifBornePersoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__verifBornePersoResponse->soap_get(soap, "ns1:verifBornePersoResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
